name:                productsAPI
version:             0.1.0.0
github:              "FabianVegaA/productsAPI"
license:             BSD3
author:              "Fabián Vega"
maintainer:          "example@example.com"
copyright:           "2022 Fabián Vega"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            A simple API REST example made with Haskell and Scotty.
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/FabianVegaA/productsAPI#readme>

dependencies:
- base >= 4.7 && < 5
- scotty == 0.12
- postgresql-simple == 0.6.4
- text == 1.2.4.1
- aeson == 2.1.0.0
- http-types == 0.12.3

library:
  source-dirs: src

executables:
  productsAPI-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - productsAPI

tests:
  productsAPI-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - productsAPI
